# Generated by Django 5.1.7 on 2025-03-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itself', models.TextField()),
                ('writer', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
